alias meow='cat'
alias ll='ls -la'
alias ..='cd ..'
alias ...='cd .. ; cd ..'

alias jupyter-start='/usr/bin/jupyter-notebook ~/jupyter/ &'
alias jupyter-stop='/bin/kill $(pgrep jupyter)'

export PATH=$PATH:/home/sizzle/bin
export EDITOR=vi

shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000

# powered by newsapi.org
getnews () {
   curl https://newsapi.org/v2/top-headlines -s -G \
      -d sources=$1 \
      -d apiKey=apikeyhere \
   | jq '.articles[] | .title'
}
